"""Add production onboarding models

Revision ID: ee2ad78d66d6
Revises: 
Create Date: 2026-06-22 16:03:53.208206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee2ad78d66d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('onboarding_records')
#     op.add_column('onboarding_activities', sa.Column('tenant_id', sa.String(length=50), nullable=True))
#     op.add_column('onboarding_activities', sa.Column('onboarding_new_hire_id', sa.Integer(), nullable=True))
#     op.alter_column('onboarding_activities', 'action',
#                existing_type=mysql.VARCHAR(length=100),
#                type_=sa.String(length=200),
#                existing_nullable=False)
#     op.alter_column('onboarding_activities', 'created_at',
#                existing_type=mysql.DATETIME(),
#                nullable=False,
#                existing_server_default=sa.text('(now())'))
#     op.create_index(op.f('ix_onboarding_activities_tenant_id'), 'onboarding_activities', ['tenant_id'], unique=False)
#     op.create_foreign_key(None, 'onboarding_activities', 'onboarding_new_hires', ['onboarding_new_hire_id'], ['id'])
#     op.drop_column('onboarding_activities', 'onboarding_record_id')
#     # ### end Alembic commands ###

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('onboarding_records')  <-- Comment this line out!
    op.add_column('onboarding_activities', sa.Column('tenant_id', sa.String(length=50), nullable=True))
    op.add_column('onboarding_activities', sa.Column('onboarding_new_hire_id', sa.Integer(), nullable=True))
    op.alter_column('onboarding_activities', 'action',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('onboarding_activities', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.create_index(op.f('ix_onboarding_activities_tenant_id'), 'onboarding_activities', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'onboarding_activities', 'onboarding_new_hires', ['onboarding_new_hire_id'], ['id'])
    op.drop_column('onboarding_activities', 'onboarding_record_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_activities', sa.Column('onboarding_record_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'onboarding_activities', type_='foreignkey')
    op.create_foreign_key('onboarding_activities_ibfk_1', 'onboarding_activities', 'onboarding_records', ['onboarding_record_id'], ['id'])
    op.drop_index(op.f('ix_onboarding_activities_tenant_id'), table_name='onboarding_activities')
    op.alter_column('onboarding_activities', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('onboarding_activities', 'action',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('onboarding_activities', 'onboarding_new_hire_id')
    op.drop_column('onboarding_activities', 'tenant_id')
    op.create_table('onboarding_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('joining_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('OFFER_SENT', 'OFFER_ACCEPTED', 'PRE_JOINING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='onboarding_records_ibfk_2'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='onboarding_records_ibfk_1'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name='onboarding_records_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_onboarding_records_id', 'onboarding_records', ['id'], unique=False)
    op.create_index('ix_onboarding_records_email', 'onboarding_records', ['email'], unique=False)
    # ### end Alembic commands ###
